[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "yarn build"

[[redirects]]
  from = "/api/ctb/*"
  to = "https://rt.data.gov.hk/v2/transport/citybus/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/kmb/*"
  to = "https://data.etabus.gov.hk/v1/transport/kmb/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200