// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Keyboard: typeof import('./components/Keyboard.vue')['default']
    PlacePicker: typeof import('./components/PlacePicker.vue')['default']
  }
}

export { }
